schema:
  - ${NEXT_PUBLIC_GRAPHQL_ENDPOINT_URL}
documents: '**/*.graphql'
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
  - './lib/scripts/codegen-apollo-functions.js'
cacheDir: __generated__
