schema:
  - ${NEXT_PUBLIC_GRAPHQL_ENDPOINT_URL}:
      headers:
        'x-hasura-admin-secret': ${HASURA_ADMIN_SECRET}
documents: '**/*.graphql'
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
  - './lib/scripts/codegen-apollo-functions.js'
cacheDir: __generated__
